"""init

Revision ID: f1efaf4b9fe9
Revises: 
Create Date: 2025-07-09 19:50:24.456660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1efaf4b9fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('is_grayscale', sa.Boolean(), nullable=False),
    sa.Column('original_image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_images')
    op.drop_table('images')
    # ### end Alembic commands ###
